author:
  - Valentin Robert <valentin.robert.42@gmail.com>

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - GADTs
  - KindSignatures
  - LambdaCase
  - MonoLocalBinds
  - NamedFieldPuns
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UnicodeSyntax

dependencies:
  - base               ^>= 4.13.0.0
  - lens
  - monad-loops
  - polysemy           ^>= 1.3.0.0
  - polysemy-plugin    ^>= 0.2.5.0
  - split              ^>= 0.2.3.4
  - string-interpolate ^>= 0.2.0.0
  # # These are test dependencies, but for nix, I must put them here...
  # - filepath         ^>= 1.4.2.1
  # - tasty            ^>= 1.2.3
  # - tasty-hunit      ^>= 0.10.0.2
  # - tasty-quickcheck ^>= 0.10.1.1
  # - tasty-smallcheck ^>= 0.8.1

executables:

  day1:
    main: Day1.hs
    source-dirs: exe/day1
    dependencies:
      - advent-of-code

  day2:
    main: Day2.hs
    source-dirs: exe/day2
    dependencies:
      - advent-of-code

  day3:
    main: Day3.hs
    source-dirs: exe/day3
    dependencies:
      - advent-of-code

ghc-options:
  - -fplugin=Polysemy.Plugin
  - -Wall
  - -Werror

library:

  # dependencies:
    # - TODO ^>= 1.1.1.1

  exposed-modules:
    - Fuel
    - Intcode

  # other-modules:
    # - TODO

  source-dirs: lib

license: BSD3

name: advent-of-code

# tests:
#   test:
#     main: Main.hs
#     source-dirs: test
#     dependencies:
#       - advent-of-code-2019
#     other-modules:
#       - TODO

version: 0.1.0
